### ISSUE TITLE
java.lang.NoClassDefFoundError:  while running on latest build

### ISSUE THREAD

**Issue by kunalbuddy** [codecentric/gatling-jdbc#10]
java.lang.NoClassDefFoundError: scala/collection/compat/Factory$
	at scalikejdbc.DBSession.list(DBSession.scala:295)
	at scalikejdbc.DBSession.list$(DBSession.scala:294)
	at scalikejdbc.ActiveSession.list(DBSession.scala:837)
	at scalikejdbc.DBSessionWrapper.$anonfun$list$1(DBSessionWrapper.scala:52)
	at scalikejdbc.DBSessionWrapper.$anonfun$withAttributesSwitchedDBSession$1(DBSessionWrapper.scala:34)
	at scalikejdbc.DBSessionAttributesSwitcher.withSwitchedDBSession(DBSessionAttributesSwitcher.scala:31)
	at scalikejdbc.DBSessionWrapper.withAttributesSwitchedDBSession(DBSessionWrapper.scala:33)
	at scalikejdbc.DBSessionWrapper.list(DBSessionWrapper.scala:52)
	at scalikejdbc.SQLToList.result(SQL.scala:931)
	at scalikejdbc.SQLToList.result$(SQL.scala:930)
	at scalikejdbc.SQLToListImpl.result(SQL.scala:944)
	at scalikejdbc.SQLToListImpl.result(SQL.scala:944)
	at scalikejdbc.SQLToResult.$anonfun$apply$21(SQL.scala:811)
	at scalikejdbc.SQLToResult.apply(SQL.scala:817)
	at scalikejdbc.SQLToResult.apply$(SQL.scala:805)
	at scalikejdbc.SQLToListImpl.apply(SQL.scala:944)
	at de.codecentric.gatling.jdbc.action.JdbcSelectAction.$anonfun$execute$3(JdbcSelectAction.scala:45)
	at scalikejdbc.DBConnection.autoCommit(DBConnection.scala:242)
	at scalikejdbc.DBConnection.autoCommit$(DBConnection.scala:240)
	at scalikejdbc.DB.autoCommit(DB.scala:60)
	at scalikejdbc.DB$.$anonfun$autoCommit$1(DB.scala:216)
	at scalikejdbc.LoanPattern.using(LoanPattern.scala:18)
	at scalikejdbc.LoanPattern.using$(LoanPattern.scala:16)
	at scalikejdbc.DB$.using(DB.scala:139)
	at scalikejdbc.DB$.autoCommit(DB.scala:215)
	at de.codecentric.gatling.jdbc.action.JdbcSelectAction.$anonfun$execute$2(JdbcSelectAction.scala:44)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by rbraeunlich** [comment]
Hi @kunalbuddy 
could you please repost the issue [here](https://github.com/rbraeunlich/gatling-jdbc) and give a little bit more details what you were doing and how you were executing the simulation. Was it from the standalone Gatling, from an IDE or from the sbt plugin?
